name: 'ci-action'
description: 'Continious Integration action for go- and node- projects'
inputs:
  ignore:
    description: Folders and files that will be ignored when checking (comma separated)
    required: false
  organization:
    description: The name of the organization(s) on GitHub containing private repositories (comma separated)
    default: untillpro
  token:
    description: Auth token used to fetch dependencies from private repositories
  codecov-token:
    description: Codecov token
  codecov-go-race:
    description: 'Codecov: use Go Race Detector'
    default: true
  publish-asset:
    description: File / dir name to publish
  publish-token:
    description: Auth token used to publish
    default: ${{ github.token }}
  publish-keep:
    description: Number of kept releases (0 - all)
    default: 8
  repository:
    description: 'Repository name with owner. For example, untillpro/ci-action'
    default: ${{ github.repository }}
  run-mod-tidy:
    description: 'Only for go-projects: execute `go mod tidy`'
    default: true
  main-branch:
    description: Main branch name
    default: main
  ignore-copyright:
    description: 'Do not check the copyright in first comments of source code'
    default: false
outputs:
  release_id:
    description: 'The ID of the created Release'
  release_name:
    description: 'The name (version) of the created Release'
  release_html_url:
    description: 'The URL users can navigate to in order to view the release'
  release_upload_url:
    description: 'The URL for uploading assets to the release'
  asset_browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node16'
  main: 'dist/index.js'
