name: CI-Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.0
    - name: Checkout
      uses: actions/checkout@v3
    - name: CI
      uses: ./
      with:
        ignore: dist, .vscode
        codecov-token: ${{ secrets.CODECOV_TOKEN }}
        codecov-go-race: false
        publish-asset: ci-action.exe
        main-branch: master
      env:
        GOOS: windows
        GOARCH: 386
